name: "Tanner's Test"
favicon: null
layout_spectrum: 0.951891757780686
typography_spectrum: 0.9432755066081882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5983234962914139
  lightness: 0.22509544575586915
  saturation: 0.09748573298566043
  rhythmicContrast: 0.18954154290258884
purpose: []
